name: Deploy to api

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Deploy to API server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/dnd-12th-5-backend
            git fetch origin
            git reset --hard origin/develop
            git clean -fd
            ./gradlew clean build -x test
            cp build/libs/picktory-0.0.1-SNAPSHOT.jar /home/ec2-user/picktory-prod.jar
            sudo systemctl restart picktory.service
